In [ ]:
import scipy.io
import numpy as np

import pickle
from collections import Counter
from typing import Dict, List, Optional, Tuple

import igraph as ig
import scipy.sparse




In [1]:

mat = scipy.io.loadmat(
    r"C:\Users\Ana\OneDrive\Escritorio\ARTORG\XiangJi\ML20180815_240_c5o1_578.mat",
    struct_as_record=False,
    squeeze_me=True # This option simplifies the structure of the loaded data, making it easier to access the fields without needing to use additional indexing -> mat["link"][0,0]["cc_ind"]
)

print(mat.keys())

print(mat["label"][:10])

NameError: name 'scipy' is not defined

In [13]:
a=mat["node"].cc_ind

In [14]:
a[:10]

array([array([ 745232, 1894415, 1895487], dtype=int32), 746854,
       array([1610553, 1610554, 1611625], dtype=int32), 1770475, 1854779,
       1936430, 2061126, array([2111171, 2111172, 3259283], dtype=int32),
       array([2126058, 3276313, 3276314], dtype=int32), 2160663],
      dtype=object)

In [17]:
# If the sequence is correct, the differences between consecutive points should be:
# - 1 for steps along the main axes (x, y, or z)
# - sqrt(2) ~ 1.414 for edge steps
# - sqrt(3) ~ 1.732 for diagonal steps
# If there are large jumps in the differences, it may indicate that the sequence is not correct or that there are gaps in the skeleton.

from mat_to_pkl import lin_to_coordinates, yxz_to_xyz

# checking for link 1
cc = np.asarray(mat["link"].cc_ind[1]).astype(np.int64).ravel()
pts = yxz_to_xyz(lin_to_coordinates(cc, mat["num"].mask_size))
print(pts[:10])

diffs = np.diff(pts, axis=0)
print("diff:", np.linalg.norm(diffs, axis=1)[:20])

[[  8 951   0]
 [  9 952   1]
 [ 10 952   2]
 [ 11 953   3]
 [ 12 953   4]
 [ 13 954   5]
 [ 14 954   6]
 [ 14 954   7]
 [ 15 955   8]
 [ 16 955   9]]
diff: [1.73205081 1.41421356 1.73205081 1.41421356 1.73205081 1.41421356
 1.         1.73205081 1.41421356 1.         1.73205081 1.
 1.         1.         1.41421356 1.         1.         1.
 1.         1.        ]


In [20]:
with open(r"C:\Users\Ana\OneDrive\Escritorio\ARTORG\XiangJi\ML20180815_240_c5o1_578_mvn1.pkl", "rb") as f:
    G = pickle.load(f)

print(G.es.attributes())
print(G.vs.attributes())

print(G.es[0]["lengths2"][:20])


['points', 'lengths2', 'length', 'diameters', 'diameter', 'nkind', 'connectivity']
['coords', 'diameter', 'index']
[1.7320508075688772, 1.7320508075688772, 1.4142135623730951, 1.4142135623730951, 1.0, 1.4142135623730951, 1.0, 1.7320508075688772, 1.4142135623730951, 1.7320508075688772, 1.4142135623730951, 1.0, 1.4142135623730951, 1.4142135623730951, 1.7320508075688772, 1.0, 1.4142135623730951, 1.4142135623730951, 1.4142135623730951, 1.7320508075688772]


In [5]:
import pickle
mvn = pickle.load(open(
    r"C:\Users\Ana\OneDrive\Escritorio\ARTORG\XiangJi\ML20180815_240_c5o1_578_mvn1.pkl",
    "rb"
)
)

print(mvn.es.attributes())
print(mvn.vs.attributes())

print(mvn.vcount())
print(mvn.ecount())

['points', 'lengths2', 'length', 'diameters', 'diameter', 'nkind', 'connectivity']
['coords', 'diameter', 'index']
11732
16640


In [6]:
import scipy.io
import numpy as np

mat = scipy.io.loadmat(
    r"C:\Users\Ana\OneDrive\Escritorio\ARTORG\XiangJi\ML20180815_240_c5o1_578.mat",
    struct_as_record=False,
    squeeze_me=True,
)

node_cc = np.asarray(mat["node"].cc_ind).squeeze()
link_cc = np.asarray(mat["link"].cc_ind).squeeze()
connected = np.asarray(mat["link"].connected_node_label).astype(int)

print("node CC count:", len(node_cc))
print("link CC count:", len(link_cc))
print("connected rows:", connected.shape[0])

node CC count: 11732
link CC count: 18973
connected rows: 18973


In [8]:

connected = np.asarray(mat["link"].connected_node_label).astype(int)
open_links = np.sum((connected[:, 0] == 0) | (connected[:, 1] == 0))
closed_links = np.sum((connected[:, 0] > 0) & (connected[:, 1] > 0))

print("node CC count:", len(np.asarray(mat["node"].cc_ind).squeeze()))
print("link CC count:", len(np.asarray(mat["link"].cc_ind).squeeze()))
print("connected rows:", connected.shape[0])
print("open links:", open_links)
print("closed links:", closed_links)

node CC count: 11732
link CC count: 18973
connected rows: 18973
open links: 2333
closed links: 16640


In [1]:
import pickle
mvn = pickle.load(open(
    r"C:\Users\Ana\Downloads\graph_18_OutGeom_um_formatted_Hcut1.pkl",
    "rb"
)
)

print(mvn.es.attributes())
print(mvn.vs.attributes())

print(mvn.vcount())
print(mvn.ecount())

['nkind', 'length_steps', 'diameter', 'geom_start', 'geom_end', 'length', 'connectivity', 'points', 'lengths2', 'diameters']
['coords', 'index', 'annotation', 'diameter', 'is_border', 'border_face', 'degree']
1090
1310
